---
title: "How neotropical tree behave in monospecific timber plantation : case study of Bagasse, Angélique and Yayamadou"
author:
  - name: "Maël Leborgne"
    authsuperscript: 1*
    orcid: 0000-0000-0000-0000
  - name: "Rozenn Bourquin"
    authsuperscript: 2
affiliation:
  - affsuperscript: 1
    dptuniv: "Department / University"
    address: >
      Street address,
      Zip code,
      Country.
  - affsuperscript: 2
    dptuniv: "Department / University"
    address: >
      Street address,
      Zip code,
      Country.
corrauthor:
    email: name@company.com
    url: https://www.company.com
abstract: >
  Summary of the article.
  Mandatory.
  
  
  Use double line feed for a new paragraph.
keywords: [keyword1, keyword2, etc]
JEL: [Code1, Code2, etc, MayBeDeleted]
acknowledgements: >
  Acknowledgements. 
  
  
  May be deleted.
journalinfo: "Publication reference"
archive: "DOI: xxx/xx"
# Date format: '%Y %B %d' for distill
date: "`r format(Sys.time(), '%Y %B %d')`"
url: https://GitHubID.github.io/Repository/
github-repo: GitHubID/Repository
lang: en-US
otherlangs: [fr-FR,it]
keywordlabel: Keywords
JELlabel: JEL
acknowledgementslabel: Acknowledgements
corrauthorlabel: Corresponding author
# Author separator: \par (no quote) for one author per line, "," (between quotes) else
authorseparator: \par
bibliography: references.bib
biblio-style: chicago
toc-depth: 3
fontsize: 10pt
urlcolor: blue
preamble: >
  \hyphenation{bio-di-ver-si-ty sap-lings}
always_allow_html: yes
csquotes: true
output:
  bookdown::html_document2:
    base_format: distill::distill_article
    toc: yes
    toc_float: yes
    code_folding: show
    highlight_downlit: yes
  rmdformats::downcute:
    use_bookdown: yes
    lightbox: yes
  bookdown::gitbook:
    config:
      download: "pdf"
      sharing:
        github: yes
  bookdown::pdf_book:
    template: latex/template.tex
    citation_package: natbib
    latex_engine: xelatex
    keep_tex: yes
  bookdown::word_document2: default
editor_options: 
  markdown: 
    wrap: sentence
---

```{r}
#| label: DoNotModify
#| include: false
### Utilities. Do not modify.
# Installation of packpred if necessary
install_packpred <- function(packpred) {
  install_package <- function(package) {
    if (!package %in% installed.packages()[, 1]) {
      install.packages(package, repos = "https://cran.rstudio.com/")
    }
  }
  invisible(sapply(packpred, install_package))
}

# Basic packpred
install_packpred(c("bookdown", "formatR", "kableExtra", "ragg"))

# Chunk font size hook: allows size='small' or any valid Latex font size in chunk options
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(
    options$size != "normalsize", 
    paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), 
    x
  )
})
```

```{r}
#| label: Options
#| include: false
### Customized options for this document
# Add necessary packpred here
packpred <- c("tidyverse")
# Install them
install_packpred(packpred)

# knitr options
knitr::opts_chunk$set(
  cache =   FALSE,    # Cache chunk results
  include = TRUE,     # Show/Hide chunks
  echo =    TRUE,     # Show/Hide code
  warning = FALSE,    # Show/Hide warnings
  message = FALSE,    # Show/Hide messpred
  # Figure alignment and size
  fig.align = 'center', out.width = '80%',
  # Graphic devices (ragg_png is better than standard png)
  dev = c("ragg_png", "pdf"),
  # Code chunk format
  tidy = TRUE, tidy.opts = list(blank = FALSE, width.cutoff = 50),
  size = "scriptsize", knitr.graphics.auto_pdf = TRUE
  )
options(width = 50)

# ggplot style
library("tidyverse")
theme_set(theme_bw())
theme_update(
  panel.background = element_rect(fill = "transparent", colour = NA),
  plot.background = element_rect(fill = "transparent", colour = NA)
)
knitr::opts_chunk$set(dev.args = list(bg = "transparent"))

# Random seed
set.seed(973)
```

# Data Importation

```{r}
#| echo: false
library(tidyverse)
library(brms)

Inv_complet <- read.csv2("/home/jean/Bureau/projet-ONF-FTH/Data/Rozeen_30-10_DataPlantations_sansBR.csv", sep=";",dec = ",")

# ---- Convertion de Age_Plantation en années ----
convert_annee <- data.frame(
  "Age_Plantation" = unique(Inv_complet$Age_Plantation),
  "Age_Plantation_annee" = c(35,0,0.5,1,1.5,2,3,5,8,9,14,7,36,46,3.5,4,6,10.5,2.5,0,34,20,40,0.25,15,0.75,0.917,1.083,1.5,10,0.583,23,7,41,13,4.5)
)
Inv_complet <- left_join(Inv_complet,convert_annee,by="Age_Plantation")

# ---- Set Ht_mesure at 130 for those are set at 0 ----
Inv_complet <- Inv_complet %>%
  mutate(Ht_Mesure = ifelse(Ht_Mesure == 0, 130, Ht_Mesure))

# ---- Correction des diametres à 130cm ----
Inv_complet <- Inv_complet |>
  mutate(DBH = round(Circonférence/pi),digits=2) |>
  mutate(POM = Ht_Mesure) |>
  mutate(Taper_parameter = 0.156 - 0.023*log(DBH) - 0.021*log(POM/100)) |>
  mutate(DBHCorr = DBH/(exp(- Taper_parameter*((POM-130)/100))))

# ---- do DBHCorr = 0 if DBH = 0 ----
Inv_complet <- Inv_complet %>%
  mutate(DBHCorr = ifelse(DBH == 0, 0, DBHCorr))

# ---- Adding initial diameter and high for all trees ----
tree_with_starting_point <- unique(Inv_complet[Inv_complet$Age_Plantation_annee==0,]$Code_Arbre)
tree_no_starting_point <- unique(Inv_complet[Inv_complet$Code_Arbre %in% tree_with_starting_point,]$Code_Arbre)     
# All trees
Initial_state <- data.frame(                         # Inisialized
  "Code_Arbre" = tree_no_starting_point,
  "Age_Plantation_annee" = rep(0,length(tree_no_starting_point)),
  "DBHCorr" = rep(0,length(tree_no_starting_point)),
  "Hauteur_Totale" = rep(0,length(tree_no_starting_point))
)
# Make correspondance with Code_Essence, Nom_Vernaculaire, Famille, Genre, Espece
ref_code_espece <- Inv_complet %>% distinct(Code_Arbre, .keep_all = TRUE)                                      # first make a reference
ref_code_espece <- ref_code_espece |> select("Code_Arbre", "Nom_Vernaculaire", "Famille", "Genre", "Espece") # then select rows of interest
Initial_state   <-  left_join(Initial_state, ref_code_espece, by="Code_Arbre")                               # Make the correspondance for each Code_Arbre

# Finally Bind Initial_state to Inv_complet
Inv_complet <- bind_rows(Inv_complet,Initial_state)

# ---- as.factor for selected variables
Inv_complet$Code_Essence <- as.factor(Inv_complet$Code_Essence)
Inv_complet$Age_Plantation_annee <- as.factor(Inv_complet$Age_Plantation_annee)

# ---- Add last data (2025) ---- TODO

# ---- Check doublons age/arbre ---- TODO

# ---- Result ----
str(Inv_complet)


```

## Selection of species and sites

```{r}

# ---- Selection of species ----
select_species <- Inv_complet[Inv_complet$Nom_Vernaculaire %in% c("angelique","bagasse","yayamadou marecage"),]

# ---- Selection of sites ----
# Liste de combinaisons à exclure sous forme de vecteur (site, essence)
excluded_combinations <- data.frame(
  Nom_Vernaculaire = c("angelique", "angelique", "angelique", "angelique", "bagasse", "bagasse", "bagasse"),
  Libelle_Plantation = c("CHR02_A", "KAW03_D", "MDF01_A", "MDF01_D", "CHR02_A", "KAW03_A", "PAR19_D")
)
# Créer directement la colonne combinée 'combination' avec paste()
excluded_combinations$combination <- paste(excluded_combinations$Libelle_Plantation, excluded_combinations$Nom_Vernaculaire)
# Filtrage des combinaisons à exclure
select_species <- select_species %>%
  mutate(combination = paste(Libelle_Plantation, Nom_Vernaculaire)) %>%  # Créer la colonne de combinaison
  filter(!combination %in% excluded_combinations$combination) %>%  # Exclure les combinaisons
  select(-combination)

# ---- Result ----
select_species
```

# Data Exploration

## Table of plantations

```{r}
#| echo: false

# ---- Mat&Meth : Summary of tree inventories (Date and number of individuals) ----

# ---- Count table per sites and species ----
df_sp_plantation <- select_species %>% 
  select("Libelle_Plantation", "Nom_Vernaculaire") %>%
  table() %>% 
  addmargins() %>% 
  as.data.frame() %>%
  pivot_wider(names_from = Nom_Vernaculaire, values_from = Freq)

# ---- Extract Year for each plantation ----
df_year_plantation <- select_species %>% 
  group_by(Libelle_Plantation) %>% # for each plantation
  arrange(Age_Plantation_annee) %>% # arrange dates
  slice_head(n = 1) %>% # keep the oldest date possible
  ungroup() %>% # enable selection
  select(Libelle_Plantation,Date_Intervention,Age_Plantation_annee) %>% # remove useless informations
  filter(!is.na(Libelle_Plantation)) %>% # Removes zeros counts
  mutate(Year_of_plantation = as.integer(substr(Date_Intervention, 1, 4))) %>% # Extract the year
  select(-Date_Intervention) %>% # Date become useless 
  group_by(Libelle_Plantation) %>% # keep the minimal year for each plantation
  mutate(Year_of_plantation = min(Year_of_plantation)) %>%
  ungroup() %>% # enable selection
  mutate(Year_of_plantation = Year_of_plantation - Age_Plantation_annee) %>% # Correction of plantation years with age of tree on first inventory
  select(-Age_Plantation_annee) %>%
  mutate(Age_of_trees = 2025 - Year_of_plantation) # Add trees age

# ---- Join count and years ----
df_summary_plantation <- left_join(df_sp_plantation,df_year_plantation,by="Libelle_Plantation") %>%
  mutate(Plantation = substr(Libelle_Plantation, 1, 3)) %>% # divide Libelle_Plantation
  mutate(Subplot = substr(Libelle_Plantation, 4,nchar(Libelle_Plantation)))

# # ---- Complete name of des site de plantations ---- TODO
# df_name_plantation <- data.frame(
#   "Libelle_simplified" = c("RIS","TON","MDF","CHR","KAW","TOUL","CAC","PAR"),
#   "Name" = c("","Tonnegrande","MDF","Christine","Kaw","","","Paracou")
# )

# ---- New order of colonnes and rows ----
df_summary_plantation <- df_summary_plantation[, c("Plantation","Subplot","Year_of_plantation","Age_of_trees", "angelique","bagasse","yayamadou marecage")]  %>%
  arrange(Year_of_plantation)

# ---- Result ----
print(df_summary_plantation)
```

## DBH (exploration)

```{r}
#| echo: false

# ---- Selection of columns ----
select_col_sp <- data.frame(
  "arbre" = select_species$Code_Arbre,
  "diam" = select_species$DBHCorr,
  "Htot" = select_species$Hauteur_Totale,
  "essence" = as.factor(select_species$Nom_Vernaculaire), # as factor
  "age" = as.factor(select_species$Age_Plantation_annee), # converted in year
  "site" = as.factor(select_species$Libelle_Plantation),
  "etat" = select_species$Etat_Sanitaire
) %>% filter(!is.na(site)) %>% # remove NA site
  filter(etat != 5) # remove dead trees

# ---- angelique ----
ggplot(data = select_col_sp[select_col_sp$essence=="angelique",], aes(x = age, y = diam, color = essence)) +
  geom_boxplot() +
  facet_wrap(~site, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "DBH (cm)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

```{r}
#| echo: false

# ---- bagasse ----
ggplot(data = select_col_sp[select_col_sp$essence=="bagasse",], aes(x = age, y = diam, color = essence)) +
  geom_boxplot() +
  facet_wrap(~site, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "DBH (cm)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

```{r}
#| echo: false

# ---- yayamadou marecage ----
ggplot(data = select_col_sp[select_col_sp$essence=="yayamadou marecage",], aes(x = age, y = diam, color = essence)) +
  geom_boxplot() +
  facet_wrap(~site, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "DBH (cm)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

## Total Heigth (exploration)

```{r}
#| echo: false

# ---- angelique ----
ggplot(data = select_col_sp[select_col_sp$essence=="angelique",], aes(x = age, y = Htot, color = essence)) +
  geom_boxplot() +
  facet_wrap(~site, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "Total Height (cm)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

```{r}
#| echo: false

# ---- bagasse ----
ggplot(data = select_col_sp[select_col_sp$essence=="bagasse",], aes(x = age, y = Htot, color = essence)) +
  geom_boxplot() +
  facet_wrap(~site, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "Total Height (cm)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

```{r}
#| echo: false

# ---- yayamadou marecage ----
ggplot(data = select_col_sp[select_col_sp$essence=="yayamadou marecage",], aes(x = age, y = Htot, color = essence)) +
  geom_boxplot() +
  facet_wrap(~site, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "Total Height (cm)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

# Biomasse Estimation

## Filtering

### **Htot \~ DBH plot**

```{r}

# ---- PLOT ----
ggplot(select_species, aes(x = DBHCorr, y = Hauteur_Totale, color = Nom_Vernaculaire)) +
  geom_point(size = 0.5) +  # Créer un nuage de points
  labs(title = "Hauteur Totale vs DBH Corrigé",
       x = "DBH Corrigé (cm)",
       y = "Hauteur Totale (m)") +
  theme_minimal() +       # Utiliser un thème minimal
  theme(legend.title = element_text(size = 12), 
        legend.text = element_text(size = 10))  # Personnaliser la légende

```

### **Filter and new** **Htot \~ DBH plot**

```{r}

# ---- Filter ----
filtered_select_species <- select_species %>% 
  filter(!is.na(Libelle_Plantation)) %>% # remove NA site
  filter(Etat_Sanitaire != 5) %>% # remove dead trees
  filter(!is.na(DBHCorr)) %>% # remove NA from DBH
  filter(Hauteur_Totale>0) %>% # remove 0 from DBH
  filter(DBH>0) # remove 0 from Htot

# ---- PLOT ----
ggplot(filtered_select_species, aes(x = DBHCorr, y = Hauteur_Totale, color = Nom_Vernaculaire)) +
  geom_point(size = 0.5) +  # Créer un nuage de points
  labs(title = "Hauteur Totale vs DBH Corrigé",
       x = "DBH Corrigé (cm)",
       y = "Hauteur Totale (m)") +
  theme_minimal() +       # Utiliser un thème minimal
  theme(legend.title = element_text(size = 12), 
        legend.text = element_text(size = 10))  # Personnaliser la légende
```

## **Calculation**

```{r}
library(BIOMASS)

# --- Add Wood Density and Biomass ----
filtered_select_species <- filtered_select_species %>% 
  mutate(Wood_Density = getWoodDensity(Genre, Espece)$meanWD) %>% # Wood Density
  mutate(AGB = computeAGB(D = DBHCorr, H = Hauteur_Totale, WD = Wood_Density)) # BIOMASS

filtered_select_species # Result

```

## Biomass plots

### Angélique

```{r}
# ---- Selection ----
df <- filtered_select_species[filtered_select_species$Nom_Vernaculaire=="angelique",]

# ---- Plots ----
ggplot(data = df, aes(x = Age_Plantation_annee, y = AGB, color = Nom_Vernaculaire)) +
  geom_boxplot() +
  facet_wrap(~Libelle_Plantation, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "AGB (ton)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

### Bagasse

```{r}
# ---- Selection ----
df <- filtered_select_species[filtered_select_species$Nom_Vernaculaire=="bagasse",]

# ---- Plots ----
ggplot(data = df, aes(x = Age_Plantation_annee, y = AGB, color = Nom_Vernaculaire)) +
  geom_boxplot() +
  facet_wrap(~Libelle_Plantation, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "AGB (ton)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

### Yayamadou marécage

```{r}
# ---- Selection ----
df <- filtered_select_species[filtered_select_species$Nom_Vernaculaire=="yayamadou marecage",]

# ---- Plots ----
ggplot(data = df, aes(x = Age_Plantation_annee, y = AGB, color = Nom_Vernaculaire)) +
  geom_boxplot() +
  facet_wrap(~Libelle_Plantation, scales = "free_y") +
  labs(
    x = "Age (years)",
    y = "AGB (ton)",
    color = "Specie"
  ) +
  scale_color_manual(values = c("angelique" = "#8B0000", "yayamadou marecage" = "#00008B", "bagasse" = "#006400")) +  # Définir des couleurs spécifiques
  theme(plot.title = element_text(face = "bold", size = 14))
```

# Biomass accumulation rate

## Calculation

```{r}

filtered_select_species <- filtered_select_species %>%
  group_by(Code_Arbre) %>%
  summurise()


```

## Plot

## 2-way ANOVA model
